basePath: /api/v1
definitions:
  helper.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  user.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      passwordHash:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Bank server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bank API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: user.RegisterUserInput
        in: path
        name: id
        required: true
        type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helper.HTTPError'
      summary: Create User
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
